import { describe, it, expect } from 'vitest';
import { mkdtempSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { initializeRepo } from '../../src/cli/init.js';
import { buildCartographConfig, detectPostgresConfig, writeCartographConfig } from '../../src/cli/setup-shared.js';
import { refreshRepo } from '../../src/cli/refresh.js';

describe('Cartograph setup workflows', () => {
  it('detects PostgreSQL connection details from .env', () => {
    const repoDir = mkdtempSync(join(tmpdir(), 'cartograph-init-detect-'));
    writeFileSync(join(repoDir, '.env'), [
      'DB_CONNECTION=pgsql',
      'DB_HOST=db.internal',
      'DB_PORT=5433',
      'DB_USERNAME=cartograph',
      'DB_PASSWORD=secret',
      'DB_DATABASE=appdb',
      '',
    ].join('\n'));

    expect(detectPostgresConfig(repoDir)).toEqual({
      type: 'postgres',
      host: 'db.internal',
      port: 5433,
      user: 'cartograph',
      password: 'secret',
      database: 'appdb',
    });
  });

  it('init writes config, MCP config, and CLAUDE.md guidance', async () => {
    const repoDir = mkdtempSync(join(tmpdir(), 'cartograph-init-'));
    mkdirSync(join(repoDir, 'src'), { recursive: true });
    writeFileSync(join(repoDir, 'src', 'Foo.php'), '<?php class Foo {}');

    const result = await initializeRepo(repoDir, {
      yes: true,
      dbPath: join(repoDir, 'cartograph.db'),
    });

    expect(result.configWritten).toBe(true);
    expect(existsSync(join(repoDir, '.cartograph.yml'))).toBe(true);
    expect(readFileSync(join(repoDir, '.cartograph.yml'), 'utf-8')).toContain('path:');

    expect(result.mcpCreated).toBe(true);
    const mcp = JSON.parse(readFileSync(join(repoDir, '.mcp.json'), 'utf-8')) as {
      mcpServers: { cartograph: { args: string[] } };
    };
    expect(mcp.mcpServers.cartograph.args).toEqual(['serve', '--repo-path', repoDir]);

    const claude = readFileSync(join(repoDir, 'CLAUDE.md'), 'utf-8');
    expect(claude).toContain('<!-- CARTOGRAPH:START');
    expect(claude).toContain('cartograph_status');
  });

  it('refresh updates CLAUDE.md and removes legacy .cartograph output files', async () => {
    const repoDir = mkdtempSync(join(tmpdir(), 'cartograph-refresh-'));
    mkdirSync(join(repoDir, 'src'), { recursive: true });
    writeFileSync(join(repoDir, 'src', 'Bar.php'), '<?php class Bar {}');
    writeCartographConfig(repoDir, buildCartographConfig({
      languages: ['php'],
      databasePath: join(repoDir, 'cartograph.db'),
      schemaSource: 'migrations',
    }), { overwrite: true });

    mkdirSync(join(repoDir, '.cartograph'), { recursive: true });
    writeFileSync(join(repoDir, '.cartograph', 'CLAUDE.md'), '<!-- Generated by Cartograph. Do not edit manually. -->\n');
    writeFileSync(join(repoDir, '.cartograph', 'modules.md'), 'legacy');

    const result = await refreshRepo(repoDir);
    expect(result.claudeMdPath).toBe(join(repoDir, 'CLAUDE.md'));
    expect(readFileSync(join(repoDir, 'CLAUDE.md'), 'utf-8')).toContain('cartograph_find');
    expect(result.removedLegacyFiles).toContain('.cartograph/CLAUDE.md');
    expect(result.removedLegacyFiles).toContain('.cartograph/modules.md');
    expect(existsSync(join(repoDir, '.cartograph', 'CLAUDE.md'))).toBe(false);
  });
});
