import type { RepoStats, ConventionsData } from './generate-pipeline.js';

const MARKER_START = '<!-- CARTOGRAPH:START — Generated by `cartograph generate`. Do not edit manually. -->';
const MARKER_END = '<!-- CARTOGRAPH:END -->';

export { MARKER_START, MARKER_END };

export function generateClaudeMdSection(stats: RepoStats, conventions: ConventionsData): string {
  const lines: string[] = [];

  lines.push(MARKER_START);
  lines.push(`## Codebase Navigation (Cartograph)\n`);
  lines.push(`This codebase is indexed by Cartograph (${stats.totalFiles.toLocaleString()} files, ${stats.totalSymbols.toLocaleString()} symbols, ${stats.totalReferences.toLocaleString()} references).`);
  lines.push(`**Use these MCP tools instead of grep/find/read for codebase exploration.**\n`);

  // Workflow directive
  lines.push(`### Workflow`);
  lines.push(`1. Run \`cartograph_status\` to check if the index is fresh (warns if stale)`);
  lines.push(`2. Use \`cartograph_find\` before grepping — it searches the pre-built index`);
  lines.push(`3. Use \`cartograph_symbol\` to understand a class's relationships`);
  lines.push(`4. Use \`cartograph_compare\` for pattern-copy work (what does A have that B doesn't?)`);
  lines.push(`5. Use \`cartograph_deps\` / \`cartograph_flow\` to trace dependency chains\n`);

  // Tool reference
  lines.push(`### Available Tools\n`);
  lines.push('| Tool | What it does | Key options |');
  lines.push('|------|-------------|-------------|');
  lines.push('| `cartograph_status` | Check index health and freshness | — |');
  lines.push('| `cartograph_find` | Search symbols by name (fuzzy match — always matches anywhere in qualified name) | `kind`: filter by class/method/interface/etc. `path`: filter by file path prefix (e.g. `"app/Services"`) |');
  lines.push('| `cartograph_symbol` | Look up a class and its relationships (extends, implements, deps, dependents) | `name`: fully or partially qualified |');
  lines.push('| `cartograph_deps` | Forward dependency graph — what does this symbol depend on? | `depth`: 1-10 (default 3) |');
  lines.push('| `cartograph_dependents` | Reverse dependency lookup — what depends on this symbol? | `depth`: 1-5 (default 1) |');
  lines.push('| `cartograph_blast_radius` | What breaks if this file changes? | `depth`: 1-5 (default 2) |');
  lines.push('| `cartograph_flow` | Trace execution flow from an entrypoint (follows calls + `::class` references) | `depth`: 1-15 (default 5) |');
  lines.push('| `cartograph_compare` | Structural diff of two symbols — methods/properties in A but not B | `symbolA`, `symbolB`: fully or partially qualified |');
  lines.push('');

  // Top directories for orientation
  const topDirs = stats.directories
    .filter(d => !d.path.match(/^tests?\//i))
    .slice(0, 8);
  if (topDirs.length > 0) {
    lines.push(`### Top Directories\n`);
    lines.push('| Directory | Symbols | Primary |');
    lines.push('|-----------|---------|---------|');
    for (const dir of topDirs) {
      const kinds = dir.dominantKinds.length > 0 ? dir.dominantKinds.join(', ') : '—';
      lines.push(`| ${dir.path} | ${dir.symbolCount.toLocaleString()} | ${kinds} |`);
    }
    lines.push('');
  }

  lines.push(MARKER_END);
  return lines.join('\n');
}
