import type { RepoStats, ConventionsData } from './generate-pipeline.js';

const MARKER_START = '<!-- CARTOGRAPH:START — Generated by `cartograph generate`. Do not edit manually. -->';
const MARKER_END = '<!-- CARTOGRAPH:END -->';

export { MARKER_START, MARKER_END };

export function generateClaudeMdSection(stats: RepoStats, conventions: ConventionsData): string {
  const lines: string[] = [];

  lines.push(MARKER_START);
  lines.push(`## Codebase Navigation (Cartograph)\n`);
  lines.push(`This codebase is indexed by Cartograph (${stats.totalFiles.toLocaleString()} files, ${stats.totalSymbols.toLocaleString()} symbols, ${stats.totalReferences.toLocaleString()} references).`);
  lines.push(`**Use these MCP tools instead of grep/find/read for codebase exploration.**\n`);

  // Workflow directive
  lines.push(`### Workflow`);
  lines.push(`1. Run \`cartograph_status\` to check if the index is fresh (warns if stale)`);
  lines.push(`2. For database work, use \`cartograph_schema\` to discover tables before guessing names`);
  lines.push(`3. Use \`cartograph_table\` for exact current table shape (columns + inbound/outbound foreign keys)`);
  lines.push(`4. Use \`cartograph_table_graph\` to walk related tables by foreign keys before searching SQL files manually`);
  lines.push(`5. Use \`cartograph_table_usage\` when you need the schema↔code bridge: mapped entities, mapped columns, direct table-name references, and the upstream framework touchpoints above those references`);
  lines.push(`6. Use \`cartograph_test_targets\` after identifying the code you will touch — provide exactly one of \`symbol\`, \`file\`, or \`table\`; it uses direct test-side imports / instantiations when available, but still returns ranked suggestions rather than an exhaustive list`);
  lines.push(`7. Use \`cartograph_scaffold_plan\` when cloning an existing endpoint/module shape for a new target — it tells you which files/classes should exist, includes conventional concrete companions for Interface files, and marks which inferred targets already exist but still differ; it does not write files for you`);
  lines.push(`8. Use \`cartograph_find\` before grepping — it searches the pre-built symbol index and suggests close matches on 0 results`);
  lines.push(`9. Use \`cartograph_search_content\` when you need method-body or literal-content lookup (for example \`$this->args['recurringJobID']\`)`);
  lines.push(`10. Use \`cartograph_symbol\` with \`deep: true\` to see the full vertical stack (Route→Controller→Builder→Model) in one call`);
  lines.push(`11. Use \`cartograph_compare\` for pairwise pattern-copy work — shows what A has that B doesn't, with method bodies and wiring targets inlined`);
  lines.push(`12. Use \`cartograph_compare_many\` when comparing one reference implementation against several siblings`);
  lines.push(`13. Use \`cartograph_deps\` to trace forward dependencies — shows which method creates each edge (e.g. "via getControllerName(), line 13")`);
  lines.push(`14. Use \`cartograph_flow\` to trace execution flow — follows parent class template methods through child overrides\n`);

  // Tool reference
  lines.push(`### Available Tools\n`);
  lines.push('| Tool | What it does | Key options |');
  lines.push('|------|-------------|-------------|');
  lines.push('| `cartograph_status` | Check index health and freshness | — |');
  lines.push('| `cartograph_schema` | List or search current database tables with column and foreign-key counts. Use this first for DB work so you do not guess table names. | `query`: partial table name. `limit`: max results |');
  lines.push('| `cartograph_table` | Inspect exact current table shape from Cartograph\'s canonical schema layer, including columns and inbound/outbound foreign keys. | `name`: table name |');
  lines.push('| `cartograph_table_graph` | Traverse the foreign-key neighborhood around a table to understand adjacent tables and impact radius. | `name`: table name. `depth`: 1-5 |');
  lines.push('| `cartograph_table_usage` | Bridge schema to code: show Doctrine-style mapped entities, mapped columns, entity-based touchpoints, indexed direct table-name references, and explicit upstream framework touchpoints through table-backed adapters such as Models, Repositories, Builders, and DataObjects. Best for table→API tracing. It may still miss patterns with no explicit entity mapping, symbol reference, or table-name signal. | `name`: table name. `depth`: entity-graph depth. `limit`: max touchpoints. `includeTests`: include tests |');
  lines.push('| `cartograph_test_targets` | Suggest likely test files to update or create for a symbol, file, or table using indexed structure, naming heuristics, and direct test-side signals such as imports, instantiations, and class references. Heuristic and ranked, not exhaustive. | Exactly one of `symbol` or `file` or `table`. `limit`: max suggestions |');
  lines.push('| `cartograph_scaffold_plan` | Plan the files and class names needed to mirror a reference slice for a new target stem. Marks which inferred targets already exist, includes conventional concrete companions for Interface files, and summarizes gaps vs the reference. Rename-based planning only: it does not write files and may miss wiring outside the inferred slice. | `reference`: reference symbol. `target`: target stem or class name. `depth`: 1-6 |');
  lines.push('| `cartograph_find` | Search symbols by name (fuzzy, matches anywhere in qualified name). Path filter supports partial/substring matching. Suggests corrections on 0 results. | `kind`: class/method/interface/etc. `path`: substring match on file path (e.g. `"Route/Root/Companies"`) |');
  lines.push('| `cartograph_search_content` | Search indexed source text by literal substring and map matches back to enclosing methods/classes. Use this when grep would normally be required for method-body details. | `query`: literal text. `path`: file-path substring. `limit`: max matches |');
  lines.push('| `cartograph_symbol` | Look up a class and its relationships. With `deep: true`, shows full vertical stack: inheritance, wiring (which method → which class), concrete implementations, depth-2 wiring detail, and **context requirements** (which `$this->args`/`$this->params` keys the class consumes — answers \"can I reuse this in a different route?\"). | `name`: fully or partially qualified. `deep`: true for full stack view |');
  lines.push('| `cartograph_deps` | Forward dependency graph. Shows which method creates each edge (e.g. "via getControllerName(), line 13"). Follows `::class` references through method bodies. | `depth`: 1-10 (default 3) |');
  lines.push('| `cartograph_dependents` | Reverse dependency lookup — what depends on this symbol? | `depth`: 1-5 (default 1) |');
  lines.push('| `cartograph_blast_radius` | What breaks if this file changes? | `depth`: 1-5 (default 2) |');
  lines.push('| `cartograph_flow` | Trace execution flow from an entrypoint. Follows calls, `::class` refs, and parent class template methods (resolves `$this->getX()` through child overrides). | `depth`: 1-15 (default 5) |');
  lines.push('| `cartograph_compare` | Structural diff: methods in A but not B, **and behavioral diff of shared methods** — flags shared methods with different implementations by inlining both bodies side-by-side. Catches runtime differences like `$this->args[\'jobID\']` vs `$this->args[\'recurringJobID\']`. Shows `::class` wiring targets per method. | `symbolA`, `symbolB`: fully or partially qualified. `omitIdentical`: hide identical shared methods |');
  lines.push('| `cartograph_compare_many` | Compare one baseline symbol against several peers at once. Shows missing methods, baseline bodies for missing methods, and full inlined shared-method wiring/body diffs for methods that already exist on both sides. Identical shared methods are omitted by default. Symbol-level comparison only: it does not infer file lists. | `baseline`: reference symbol. `others`: peer symbols. `includeIdentical`: include identical shared methods |');
  lines.push('');

  lines.push(`### Tool Limits\n`);
  lines.push(`- \`cartograph_table_usage\` is strongest when the repo exposes explicit entity mappings, symbol references, or direct table-name references. It can now climb through table-backed framework adapters, but it is still not a guarantee of complete coverage for purely implicit patterns.`);
  lines.push(`- \`cartograph_test_targets\` returns ranked suggestions only. Direct test-side signals improve precision, but you should still treat the output as a shortlist rather than proof of full coverage.`);
  lines.push(`- \`cartograph_scaffold_plan\` is a planning aid, not code generation. It infers analogous files by renaming the reference slice, adds conventional Interface companions, and can still miss registrations, config, or non-pattern wiring outside that slice.`);
  lines.push(`- \`cartograph_compare_many\` compares symbols, not files or directories. Identical methods are omitted by default so the output stays focused on deltas.`);
  lines.push('');

  // Top directories for orientation
  const topDirs = stats.directories
    .filter(d => !d.path.match(/^tests?\//i))
    .slice(0, 8);
  if (topDirs.length > 0) {
    lines.push(`### Top Directories\n`);
    lines.push('| Directory | Symbols | Primary |');
    lines.push('|-----------|---------|---------|');
    for (const dir of topDirs) {
      const kinds = dir.dominantKinds.length > 0 ? dir.dominantKinds.join(', ') : '—';
      lines.push(`| ${dir.path} | ${dir.symbolCount.toLocaleString()} | ${kinds} |`);
    }
    lines.push('');
  }

  lines.push(MARKER_END);
  return lines.join('\n');
}
