import type { RepoStats, ConventionsData } from './generate-pipeline.js';

const MARKER_START = '<!-- CARTOGRAPH:START — Generated by `cartograph generate`. Do not edit manually. -->';
const MARKER_END = '<!-- CARTOGRAPH:END -->';

export { MARKER_START, MARKER_END };

export function generateClaudeMdSection(stats: RepoStats, conventions: ConventionsData): string {
  const lines: string[] = [];

  lines.push(MARKER_START);
  lines.push(`## Codebase Navigation (Cartograph)\n`);
  lines.push(`This codebase is indexed by Cartograph (${stats.totalFiles.toLocaleString()} files, ${stats.totalSymbols.toLocaleString()} symbols, ${stats.totalReferences.toLocaleString()} references).`);
  lines.push(`**Use these MCP tools instead of grep/find/read for codebase exploration.**\n`);

  // Workflow directive
  lines.push(`### Workflow`);
  lines.push(`1. Run \`cartograph_status\` to check if the index is fresh (warns if stale)`);
  lines.push(`2. Use \`cartograph_find\` before grepping — it searches the pre-built index`);
  lines.push(`3. Use \`cartograph_symbol\` with \`deep: true\` to see the full vertical stack (Route→Controller→Builder→Model) in one call`);
  lines.push(`4. Use \`cartograph_compare\` for pattern-copy work — shows what A has that B doesn't, with method bodies and wiring targets inlined`);
  lines.push(`5. Use \`cartograph_deps\` to trace forward dependencies — shows which method creates each edge (e.g. "via getControllerName(), line 13")`);
  lines.push(`6. Use \`cartograph_flow\` to trace execution flow — follows parent class template methods through child overrides\n`);

  // Tool reference
  lines.push(`### Available Tools\n`);
  lines.push('| Tool | What it does | Key options |');
  lines.push('|------|-------------|-------------|');
  lines.push('| `cartograph_status` | Check index health and freshness | — |');
  lines.push('| `cartograph_find` | Search symbols by name (fuzzy, matches anywhere in qualified name). Path filter supports partial/substring matching. Suggests corrections on 0 results. | `kind`: class/method/interface/etc. `path`: substring match on file path (e.g. `"Route/Root/Companies"`) |');
  lines.push('| `cartograph_symbol` | Look up a class and its relationships. With `deep: true`, shows full vertical stack: inheritance, wiring (which method → which class), concrete implementations, and depth-2 wiring detail. | `name`: fully or partially qualified. `deep`: true for full stack view |');
  lines.push('| `cartograph_deps` | Forward dependency graph. Shows which method creates each edge (e.g. "via getControllerName(), line 13"). Follows `::class` references through method bodies. | `depth`: 1-10 (default 3) |');
  lines.push('| `cartograph_dependents` | Reverse dependency lookup — what depends on this symbol? | `depth`: 1-5 (default 1) |');
  lines.push('| `cartograph_blast_radius` | What breaks if this file changes? | `depth`: 1-5 (default 2) |');
  lines.push('| `cartograph_flow` | Trace execution flow from an entrypoint. Follows calls, `::class` refs, and parent class template methods (resolves `$this->getX()` through child overrides). | `depth`: 1-15 (default 5) |');
  lines.push('| `cartograph_compare` | Structural diff: methods in A but not B, **and behavioral diff of shared methods** — flags shared methods with different implementations by inlining both bodies side-by-side. Catches runtime differences like `$this->args[\'jobID\']` vs `$this->args[\'recurringJobID\']`. Shows `::class` wiring targets per method. | `symbolA`, `symbolB`: fully or partially qualified |');
  lines.push('');

  // Top directories for orientation
  const topDirs = stats.directories
    .filter(d => !d.path.match(/^tests?\//i))
    .slice(0, 8);
  if (topDirs.length > 0) {
    lines.push(`### Top Directories\n`);
    lines.push('| Directory | Symbols | Primary |');
    lines.push('|-----------|---------|---------|');
    for (const dir of topDirs) {
      const kinds = dir.dominantKinds.length > 0 ? dir.dominantKinds.join(', ') : '—';
      lines.push(`| ${dir.path} | ${dir.symbolCount.toLocaleString()} | ${kinds} |`);
    }
    lines.push('');
  }

  lines.push(MARKER_END);
  return lines.join('\n');
}
