import type Database from 'better-sqlite3';
import fg from 'fast-glob';
import { parse as parseDotenv } from 'dotenv';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'fs';
import { dirname, resolve } from 'path';
import { homedir } from 'os';
import { parse as parseYaml } from 'yaml';
import { GeneratePipeline } from '../output/generate-pipeline.js';
import { injectSection } from '../output/claudemd-injector.js';
import type { CartographConfig, PostgresSchemaSourceConfig } from '../types.js';

const GENERATED_HEADER = '<!-- Generated by Cartograph. Do not edit manually. -->';
const LEGACY_OUTPUT_FILES = ['CLAUDE.md', 'modules.md', 'dependencies.md', 'conventions.md'];
const DEFAULT_DB_PATH = resolve(homedir(), '.cartograph', 'cartograph.db');
const DEFAULT_EXCLUDES = ['vendor/', 'node_modules/', '.git/'];

export interface ClaudeMdUpdateResult {
  path: string;
  verb: 'Added' | 'Updated';
  removedLegacyFiles: string[];
}

export interface McpConfigUpdateResult {
  path: string;
  created: boolean;
}

export function findClaudeMd(repoPath: string): string {
  const absoluteRepoPath = resolve(repoPath);
  const rootPath = `${absoluteRepoPath}/CLAUDE.md`;
  if (existsSync(rootPath)) return rootPath;

  const dotClaudePath = `${absoluteRepoPath}/.claude/CLAUDE.md`;
  if (existsSync(dotClaudePath)) return dotClaudePath;

  return rootPath;
}

export function updateClaudeMdSection(
  db: Database.Database,
  repoPath: string,
  claudeMdPath?: string
): ClaudeMdUpdateResult {
  const absoluteRepoPath = resolve(repoPath);
  const pipeline = new GeneratePipeline(db);
  const section = pipeline.generateClaudeMdContent(absoluteRepoPath);
  const targetPath = claudeMdPath ? resolve(claudeMdPath) : findClaudeMd(absoluteRepoPath);
  const existing = existsSync(targetPath)
    ? readFileSync(targetPath, 'utf-8')
    : '';

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, injectSection(existing, section));

  return {
    path: targetPath,
    verb: existing.includes('CARTOGRAPH:START') ? 'Updated' : 'Added',
    removedLegacyFiles: cleanupLegacyCartographOutputs(absoluteRepoPath),
  };
}

export function cleanupLegacyCartographOutputs(repoPath: string): string[] {
  const outputDir = resolve(repoPath, '.cartograph');
  if (!existsSync(outputDir)) {
    return [];
  }

  const removed: string[] = [];
  for (const name of LEGACY_OUTPUT_FILES) {
    const path = resolve(outputDir, name);
    if (!existsSync(path)) {
      continue;
    }

    if (name === 'CLAUDE.md') {
      const content = readFileSync(path, 'utf-8');
      if (!content.startsWith(GENERATED_HEADER)) {
        continue;
      }
    }

    rmSync(path, { force: true });
    removed.push(`.cartograph/${name}`);
  }

  if (removed.length > 0 && existsSync(outputDir) && readdirSync(outputDir).length === 0) {
    rmSync(outputDir, { recursive: true, force: true });
  }

  return removed;
}

export function detectLanguages(repoPath: string): string[] {
  const matches = fg.sync(['**/*.php', '**/*.sql'], {
    cwd: resolve(repoPath),
    onlyFiles: true,
    ignore: ['vendor/**', 'node_modules/**', '.git/**'],
    dot: false,
  });

  const languages = new Set<string>();
  for (const match of matches) {
    if (match.endsWith('.php')) languages.add('php');
    if (match.endsWith('.sql')) languages.add('sql');
  }

  return languages.size > 0 ? [...languages] : ['php'];
}

export function detectPostgresConfig(repoPath: string): Partial<PostgresSchemaSourceConfig> | null {
  for (const candidate of ['.env', '.env.local', '.env.dist', '.env.example']) {
    const path = resolve(repoPath, candidate);
    if (!existsSync(path)) {
      continue;
    }

    const detected = parsePostgresDotenv(readFileSync(path, 'utf-8'));
    if (detected) {
      return detected;
    }
  }

  for (const candidate of ['config/packages/doctrine.yaml', 'config/packages/doctrine.yml']) {
    const path = resolve(repoPath, candidate);
    if (!existsSync(path)) {
      continue;
    }

    const detected = parseDoctrineYaml(readFileSync(path, 'utf-8'));
    if (detected) {
      return detected;
    }
  }

  return null;
}

export function writeCartographConfig(
  repoPath: string,
  config: CartographConfig,
  opts: { overwrite?: boolean } = {}
): { path: string; written: boolean } {
  const configPath = resolve(repoPath, '.cartograph.yml');
  if (existsSync(configPath) && !opts.overwrite) {
    return { path: configPath, written: false };
  }

  writeFileSync(configPath, renderCartographConfig(config));
  return { path: configPath, written: true };
}

export function upsertMcpConfig(
  repoPath: string,
  mcpPath?: string
): McpConfigUpdateResult {
  const absoluteRepoPath = resolve(repoPath);
  const targetPath = mcpPath
    ? resolve(mcpPath)
    : resolve(absoluteRepoPath, '.mcp.json');
  const alreadyExists = existsSync(targetPath);
  const existing = existsSync(targetPath)
    ? JSON.parse(readFileSync(targetPath, 'utf-8')) as Record<string, unknown>
    : {};

  const mcpServers = isRecord(existing.mcpServers) ? existing.mcpServers : {};
  mcpServers.cartograph = {
    command: 'cartograph',
    args: ['serve', '--repo-path', absoluteRepoPath],
  };

  const next = {
    ...existing,
    mcpServers,
  };

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, `${JSON.stringify(next, null, 2)}\n`);

  return {
    path: targetPath,
    created: !alreadyExists,
  };
}

export function buildCartographConfig(params: {
  languages: string[];
  databasePath?: string;
  schemaSource?: 'migrations' | 'postgres';
  postgres?: Partial<PostgresSchemaSourceConfig>;
}): CartographConfig {
  const schemaSource = params.schemaSource === 'postgres'
    ? {
        type: 'postgres' as const,
        host: params.postgres?.host || 'localhost',
        port: params.postgres?.port || 5434,
        user: params.postgres?.user || 'pgsql',
        password: params.postgres?.password || 'example',
        database: params.postgres?.database || 'two',
      }
    : { type: 'migrations' as const };

  return {
    languages: params.languages.length > 0 ? params.languages : ['php'],
    exclude: [...DEFAULT_EXCLUDES],
    additionalSources: [],
    schemaSource,
    database: {
      path: params.databasePath || DEFAULT_DB_PATH,
    },
  };
}

function renderCartographConfig(config: CartographConfig): string {
  const lines: string[] = [];
  lines.push('languages:');
  for (const language of config.languages) {
    lines.push(`  - ${language}`);
  }
  lines.push('');
  lines.push('exclude:');
  for (const entry of config.exclude) {
    lines.push(`  - ${entry}`);
  }
  lines.push('');
  lines.push('additional_sources: []');
  lines.push('');
  lines.push('schema_source:');
  lines.push(`  type: ${config.schemaSource?.type || 'migrations'}`);
  if (config.schemaSource?.type === 'postgres') {
    lines.push(`  host: ${config.schemaSource.host || 'localhost'}`);
    lines.push(`  port: ${config.schemaSource.port || 5434}`);
    lines.push(`  user: ${config.schemaSource.user || 'pgsql'}`);
    lines.push(`  password: ${config.schemaSource.password || 'example'}`);
    lines.push(`  database: ${config.schemaSource.database || 'two'}`);
  }
  lines.push('');
  lines.push('database:');
  lines.push(`  path: ${config.database.path}`);
  lines.push('');
  return lines.join('\n');
}

function parsePostgresDotenv(raw: string): Partial<PostgresSchemaSourceConfig> | null {
  const env = parseDotenv(raw);
  const databaseUrl = env.DATABASE_URL || env.DB_URL;
  if (databaseUrl) {
    const detectedFromUrl = parsePostgresUrl(databaseUrl);
    if (detectedFromUrl) {
      return detectedFromUrl;
    }
  }

  const connection = (env.DB_CONNECTION || '').toLowerCase();
  if (connection && connection !== 'pgsql' && connection !== 'postgres' && connection !== 'postgresql') {
    return null;
  }

  if (!env.DB_HOST && !env.DB_DATABASE && !env.DB_PORT && !env.DB_USERNAME && !env.DB_USER) {
    return null;
  }

  return {
    type: 'postgres',
    host: env.DB_HOST || 'localhost',
    port: parseOptionalNumber(env.DB_PORT) || 5432,
    user: env.DB_USERNAME || env.DB_USER || 'postgres',
    password: env.DB_PASSWORD || '',
    database: env.DB_DATABASE || 'postgres',
  };
}

function parseDoctrineYaml(raw: string): Partial<PostgresSchemaSourceConfig> | null {
  try {
    const parsed = parseYaml(raw) as Record<string, unknown> | null;
    const url = readNestedString(parsed, ['doctrine', 'dbal', 'url']);
    if (url) {
      return parsePostgresUrl(url);
    }
  } catch {
    return null;
  }

  return null;
}

function parsePostgresUrl(value: string): Partial<PostgresSchemaSourceConfig> | null {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return null;
  }

  if (!['postgres:', 'postgresql:'].includes(url.protocol)) {
    return null;
  }

  return {
    type: 'postgres',
    host: url.hostname || 'localhost',
    port: parseOptionalNumber(url.port) || 5432,
    user: decodeURIComponent(url.username || 'postgres'),
    password: decodeURIComponent(url.password || ''),
    database: url.pathname.replace(/^\//, '') || 'postgres',
  };
}

function parseOptionalNumber(value: string | undefined): number | undefined {
  if (!value) return undefined;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function readNestedString(
  value: Record<string, unknown> | null,
  keys: string[]
): string | null {
  let current: unknown = value;
  for (const key of keys) {
    if (!isRecord(current) || typeof current[key] === 'undefined') {
      return null;
    }
    current = current[key];
  }
  return typeof current === 'string' ? current : null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
