import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import Database from 'better-sqlite3';
import { openDatabase } from '../../src/db/connection.js';
import { runMigrations } from '../../src/db/migrate.js';
import { IndexPipeline } from '../../src/indexer/pipeline.js';
import { join } from 'path';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import type { CartographConfig } from '../../src/types.js';
import { updateClaudeMdSection } from '../../src/cli/setup-shared.js';

const FIXTURES = join(import.meta.dirname, '..', 'fixtures', 'laravel-sample');
const ROOT_CLAUDE = join(FIXTURES, 'CLAUDE.md');
const DOT_CLAUDE = join(FIXTURES, '.claude', 'CLAUDE.md');
const LEGACY_DIR = join(FIXTURES, '.cartograph');

function testConfig(): CartographConfig {
  return {
    languages: ['php'],
    exclude: ['vendor/'],
    additionalSources: [],
    database: { path: ':memory:' },
  };
}

describe('Generate CLAUDE.md integration', () => {
  let db: Database.Database;

  beforeAll(() => {
    db = openDatabase({ path: ':memory:' });
    runMigrations(db);
  });

  afterAll(() => {
    cleanupGeneratedFiles();
    db.close();
  });

  beforeEach(() => {
    db.exec('DELETE FROM symbol_references');
    db.exec('DELETE FROM symbol_column_links');
    db.exec('DELETE FROM symbol_table_links');
    db.exec('DELETE FROM symbols');
    db.exec('DELETE FROM files');
    db.exec('DELETE FROM repos');
    cleanupGeneratedFiles();
  });

  it('injects a Cartograph section into CLAUDE.md', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    const result = updateClaudeMdSection(db, FIXTURES);
    expect(result.verb).toBe('Added');
    expect(result.path).toBe(ROOT_CLAUDE);
    expect(existsSync(ROOT_CLAUDE)).toBe(true);

    const content = readFileSync(ROOT_CLAUDE, 'utf-8');
    expect(content).toContain('<!-- CARTOGRAPH:START');
    expect(content).toContain('cartograph_status');
    expect(content).toContain('cartograph_table_usage');
  });

  it('prefers .claude/CLAUDE.md when present and root CLAUDE.md is absent', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    mkdirSync(join(FIXTURES, '.claude'), { recursive: true });
    writeFileSync(DOT_CLAUDE, '# Claude\n');

    const result = updateClaudeMdSection(db, FIXTURES);
    expect(result.path).toBe(DOT_CLAUDE);
    expect(readFileSync(DOT_CLAUDE, 'utf-8')).toContain('cartograph_find');
    expect(existsSync(ROOT_CLAUDE)).toBe(false);
  });

  it('removes legacy generated .cartograph files', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    mkdirSync(LEGACY_DIR, { recursive: true });
    writeFileSync(join(LEGACY_DIR, 'CLAUDE.md'), '<!-- Generated by Cartograph. Do not edit manually. -->\n');
    writeFileSync(join(LEGACY_DIR, 'modules.md'), 'legacy');
    writeFileSync(join(LEGACY_DIR, 'dependencies.md'), 'legacy');
    writeFileSync(join(LEGACY_DIR, 'conventions.md'), 'legacy');

    const result = updateClaudeMdSection(db, FIXTURES);
    expect(result.removedLegacyFiles).toEqual([
      '.cartograph/CLAUDE.md',
      '.cartograph/modules.md',
      '.cartograph/dependencies.md',
      '.cartograph/conventions.md',
    ]);
    expect(existsSync(LEGACY_DIR)).toBe(false);
  });

  it('is idempotent across repeated runs', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    updateClaudeMdSection(db, FIXTURES);
    const first = readFileSync(ROOT_CLAUDE, 'utf-8');

    updateClaudeMdSection(db, FIXTURES);
    const second = readFileSync(ROOT_CLAUDE, 'utf-8');

    expect(first).toBe(second);
  });
});

function cleanupGeneratedFiles(): void {
  for (const path of [ROOT_CLAUDE, DOT_CLAUDE, LEGACY_DIR]) {
    if (existsSync(path)) {
      rmSync(path, { recursive: true, force: true });
    }
  }

  const dotClaudeDir = join(FIXTURES, '.claude');
  if (existsSync(dotClaudeDir)) {
    rmSync(dotClaudeDir, { recursive: true, force: true });
  }
}
